set -g mouse on

# Open new split panes in the current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Optional: Also open new windows in the current directory
bind c new-window -c "#{pane_current_path}"

# Copy to clipboard
if-shell 'uname | grep -q Linux' {
  set -s copy-command 'xclip -selection clipboard'
}
if-shell 'uname | grep -q Darwin' {
  set -s copy-command 'pbcopy'
}
