set -g mouse on

# Automatically rename window to current working directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

set-option -g focus-events on

# When opening pane or window, use current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Copy to clipboard
if-shell 'uname | grep -q Linux' {
  set -s copy-command 'xclip -selection clipboard'
}
if-shell 'uname | grep -q Darwin' {
  set -s copy-command 'pbcopy'
}
